[tool.yapfignore]
ignore_patterns = [
    ".env/**",
    ".pytest_cache/**",
    "dist/**",
    "docs/**",
]

[tool.yapf]
based_on_style = "pep8"
spaces_before_comment = 4
column_limit = 99
split_before_logical_operator = true