#!/bin/sh

# Sets up the environment to run the tests
bash ./bootstrap

# Allow tests to run in the virtual environment.
. bin/activate

# Move to root of volttron project
cd volttron

# Run all tests volttron.
nose --with-xunit
