- import_playbook: includes/ensure_host_keys.yml

- hosts: all
  tasks:
    - include_tasks: includes/ansible_venv.yml
    - name: Configure VOLTTRON Instances
      volttron_instance_config:
        config_file: "{{ ansible_env.HOME }}/host.config.yml"
        state: "STOPPED"
        phase: "UNINSTALL"
      register: instance_state

    - name: Remove vollttron directory, files and other volttron artifacts
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - "{{ ansible_env.HOME }}/volttron"
        - "{{ ansible_env.HOME }}/.volttron"
        - "{{ ansible_env.HOME }}/host.config.yml"
        - "{{ ansible_env.HOME }}/rabbitmq_server"
        - "{{ ansible_env.HOME }}/.volttron_rmq_home"
        - "{{ ansible_env.HOME }}/.volttron_instances"
        - "{{ ansible_env.HOME }}/ansible_logging.log"
        - "{{ ansible_env.HOME }}/logfile.log"
        - "{{ ansible_env.HOME }}/configs"
        - "{{ ansible_env.HOME }}/volttron.tar.gz"
        - "{{ ansible_env.HOME }}/ansible_venv"

