---
- hosts: all
#  become: yes
#  become_method: sudo
#  gather_facts: True
  environment:
    VOLTTRON_HOME: "{{ ansible_env.HOME }}/.volttron"
    VOLTTRON_ROOT: "{{ ansible_env.HOME }}/volttron"
    HOST_CONFIG: "{{ ansible_env.HOME }}/host.config.yml"
  vars:
    # Ansible will use this path on remote hosts to run the interpreter with.
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - include_tasks: includes/ansible_venv.yml
    - include_tasks: includes/update_facts.yml
      vars:
        host_config: "{{ ansible_env.HOME }}/host.config.yml"

    - debug:
        var: volttron_host_facts #"MY host facts are:\n{{ volttron_host_facts | to_json }}"
#
#    - name: Retrieving Status
#      volttron_instance_config:
#        config_file: "{{ ansible_env.HOME }}/host.config.yml"
#      check_mode: True
#      register: instance_state
#
#    - debug:
#        var: instance_state
