---
- import_playbook: includes/ensure_host_keys.yml

- hosts: all
#  become: yes
#  become_method: sudo
  environment:
    VOLTTRON_HOME: "{{ ansible_env.HOME }}/.volttron"
    VOLTTRON_ROOT: "{{ ansible_env.HOME }}/volttron"
    HOST_CONFIG: "{{ ansible_env.HOME }}/host.config.yml"
  vars:
    # Ansible will use this path on remote hosts to run the interpreter with.
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - include_tasks: includes/common.yml

    - name: Retrieving Status
      volttron_instance_config:
        config_file: "{{ host_config }}"
      check_mode: True
      register: instance_state

    - debug:
        var: instance_state
