---
- import_playbook: includes/ensure_host_keys.yml

- hosts: all
  tasks:
    - include_tasks: includes/ansible_venv.yml
    - name: Configure VOLTTRON Instances
      volttron_instance_config:
        config_file: "{{ ansible_env.HOME }}/host.config.yml"
        state: "STOPPED"
      register: instance_state

    - debug:
        var: instance_state
