---
all:
    hosts:
        web:
            ansible_host: 192.168.56.120
            ansible_user: vagrant
            enable_web: "yes"
        collector1:
            ansible_host: 192.168.56.121
            ansible_user: vagrant
            # Note this is the only place where we use messagebus
            # rather than message-bus, due to message-bus is not
            # a valid variable for python.
            messagebus: rmq
            enable_drivers: yes
        collector2:
            ansible_host: 192.168.56.122
            ansible_user: vagrant
            enable_drivers: yes
