---
all:
    hosts:
        web:
            ansible_host: 192.168.44.10
            ansible_user: vagrant
            enable_web: yes
        collector1:
            ansible_host: 192.168.44.11
            ansible_user: vagrant
            # Note this is the only place where we use messagebus
            # rather than message-bus, due to message-bus is not
            # a valid variable for python.
            messagebus: rmq
            enable_drivers: yes
        collector2:
            ansible_host: 192.168.44.12
            ansible_user: vagrant
            enable_drivers: yes
