FROM amd64/ubuntu:focal

SHELL [ "bash", "-c" ]

USER root
RUN set -eux; apt-get update --fix-missing; apt-get install -y --no-install-recommends \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel

RUN pip3 install 'bacpypes==0.16.7'

COPY ./bacnet_device_fixture.py /code/bacnet_device_fixture.py

CMD ["python3", "/code/bacnet_device_fixture.py"]
