VOLTTRON_CENTRAL = 'volttron.central'
VOLTTRON_CENTRAL_PLATFORM = 'platform.agent'

PLATFORM_HISTORIAN = 'platform.historian'
CONTROL = 'control'
CONTROL_CONNECTION = 'control.connection'
MASTER_WEB = 'master.web'

all_known = (VOLTTRON_CENTRAL, VOLTTRON_CENTRAL_PLATFORM, PLATFORM_HISTORIAN,
             CONTROL, CONTROL_CONNECTION, MASTER_WEB)
