---
- name: "Raspbian-specific ansible venv packages"
  pip:
    virtualenv: "{{ ansible_env.HOME }}/ansible_venv"
    virtualenv_command: /usr/bin/python3 -m venv
    name:
      - cython
  when: ansible_lsb.id == "Raspbian"

# Use anisible interperet to separate the volttron requirements from
# the requirements of the volttron instance
- name: Create ansbile virtual env
  pip:
    virtualenv: "{{ ansible_env.HOME }}/ansible_venv"
    virtualenv_command: /usr/bin/python3 -m venv
    name:
     - pyyaml
     - psutil
     - zmq
     - 'netifaces==0.10.9'
     - 'deepdiff'

# Sets the ansible interpreter to be the one that
# is used for the rest of the tasks.
- name: Set ansible interpreter
  set_fact:
    ansible_python_interpreter: "{{ ansible_env.HOME }}/ansible_venv/bin/python"
