---
- name: Set default values
  set_fact:
    ansible_python_interpreter: /usr/bin/python3
    volttron_home: "{{ volttron_home | default('{{ ansible_env.HOME }}/.volttron') }}"
    volttron_root: "{{ volttron_root | default('{{ ansible_env.HOME }}/volttron') }}"
    host_config: "{{ host_config | default('{{ ansible_env.HOME }}/host.config.yml') }}"
    host_configs_dir: "{{ host_configs_dir | default('{{ ansible_env.HOME }}/configs') }}"
    enable_web: no
    enable_drivers: yes
    messagebus: zmq
    http_proxy: ''
    my_ansible_vitualenv: "{{ my_ansible_vitualenv | default('{{ansible_env.HOME }}/ansible_venv') }}"
    my_ansible_python_interpreter: "{{ my_ansible_vitualenv | default('{{ansible_env.HOME }}/ansible_venv')}}/bin/python"
